// const initialMovies = [
//   {
//     id: 1,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design2.png",
//     saved: false,
//   },
//   {
//     id: 2,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design2.png",
//     saved: false,
//   },
//   {
//     id: 3,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design3.png",
//     saved: true,
//   },
//   {
//     id: 4,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design4.png",
//     saved: false,
//   },
//   {
//     id: 5,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design5.png",
//     saved: true,
//   },
//   {
//     id: 6,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design6.png",
//     saved: false,
//   },
//   {
//     id: 7,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design7.png",
//     saved: false,
//   },
//   {
//     id: 8,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design8.png",
//     saved: false,
//   },
//   {
//     id: 9,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design9.png",
//     saved: false,
//   },
//   {
//     id: 10,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design10.png",
//     saved: true,
//   },
//   {
//     id: 11,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design11.png",
//     saved: false,
//   },
//   {
//     id: 12,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design12.png",
//     saved: false,
//   },
//   {
//     id: 13,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design12.png",
//     saved: false,
//   },
//   {
//     id: 14,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design12.png",
//     saved: false,
//   },
//   {
//     id: 15,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design12.png",
//     saved: false,
//   },
//   {
//     id: 16,
//     title: "33 слова о дизайне",
//     duration: "1ч 42м",
//     image: "https://www.linkpicture.com/q/design12.png",
//     saved: false,
//   }
// ];

// const savedMovies = [
//   {
//       id: 1,
//       title: '33 слова о дизайне',
//       duration: '1ч 42м',
//       image: 'https://www.linkpicture.com/q/design2.png',
//       saved: false,
//   },
//   {
//       id: 2,
//       title: '33 слова о дизайне',
//       duration: '1ч 42м',
//       image: 'https://www.linkpicture.com/q/design2.png',
//       saved: false,
//   },
//   {
//       id: 3,
//       title: '33 слова о дизайне',
//       duration: '1ч 42м',
//       image: 'https://www.linkpicture.com/q/design2.png',
//       saved: false,
//   },
// ];

// export {initialMovies, savedMovies};